### ISSUE TITLE
[FEAT] 찜 CRUD 기능 개발

### ISSUE THREAD

**Issue by hayeon1ee** [Gray-Pants/BE#16]
## 기능

- 찜 CRUD 구현

## 작업 내용

- 찜 하기
- 찜 취소
- 찜 조회

## 접근 및 구현
- Like와 연관된 entity 생성
- Like와 연관된 repository 생성
- Like와 연관된 service 생성
- Like와 연관된 controller 생성

## 참고
.

**Comment by Jinseonghyun** [comment]
postman으로 테스트 해보기 해보기 위해 소셜로그인 진행하는 과정에서 에러 발생

**Comment by Jinseonghyun** [comment]
postman 까지 테스트 완료된 찜하기 코드입니다.
