### ISSUE TITLE
[FEAT] BaseEntity class 생성

### ISSUE THREAD

**Issue by POKUDING** [Gray-Pants/BE#6]
## 기능
created_at, updated_at을 자동으로 입력하는 엔티티 필드를 갖고있는 base class

## 작업 내용
BaseEntity class 구현

## 접근 및 구현
- @CreatedDate, @LastModifiedDate 어노테이션을 이용하여 자동으로 생성일자 수정일자를 주입

## 참고
** 참고할 이슈 혹은 링크 등이 있으면 함께 첨부합니다. **

**Comment by juhee200** [comment]
완료했습니다!!
