### ISSUE TITLE
[FEAT] 상품CRUD 구현

### ISSUE THREAD

**Issue by jgoneit** [Gray-Pants/BE#8]
## 기능
- 상품 CRUD 구현하기

## 작업 내용
-itemController, ItemService, ItemRespository 생성, ItemDTO

## 접근 및 구현
-기본적인 CRUD 구현

## 참고
** 참고할 이슈 혹은 링크 등이 있으면 함께 첨부합니다. **

**Comment by juhee200** [comment]
완료했습니다.
